version: '3.8'

services:
  frontend:
    image: imagefront
    container_name: frontangular
    ports:
      - "8086:80"

  backend:
    image: imgbackend
    container_name: backspring
    ports:
      - "9001:8080"
    environment:
      MYSQL_HOST: mysqlcontainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: leasingdbCopie
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  

networks:
  default:
    external:
      name: networkmysql  # Use the existing network
